config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :wallets do
    collection do
      get '/:id/in', to: 'incomes#new', as: :new_income
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence:true, uniqueness:true
    validates :image, presence:true, uniqueness:true

    scope :order_by_name, -> { order("name ASC")}
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :wallet

  validates :value, presence:true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
   validates :name, presence:true, uniqueness:true

    def incomes
        @incomes = Income.where(:wallet_id=> self.id).order('created_at DESC')
    end

    def balance
        @balance = Income.where(:wallet_id => self.id).sum(:value)
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[ show edit update destroy ]

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1 or /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    if params[:id].present?
      @wallet = Wallet.find params[:id]
    end
    
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes or /incomes.json
  def create
    @income = Income.new(income_params)

    @wallet = Wallet.find(income_params['wallet_id'])
    # puts "object =>#{income_params['wallet_id']}"

    respond_to do |format|
      if @income.save
        format.html { redirect_to wallet_url(@wallet), notice: "Income was successfully created." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to income_url(@income), notice: "Income was successfully updated." }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: "Income was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:wallet_id, :value, :description)
    end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  # GET /wallets or /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1 or /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy

    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: income, class:"form") do |form| %>
  <% if income.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :wallet_id, value: wallet.id, type: :hidden %>


  <div class="flex-form">
    <%= form.label "Valor:", style: "display: block" %>
    <%= form.text_field :value, placeholder: number_to_currency(0) %>
  </div>

  <div class="flex-form">
    <%= form.text_area :description, placeholder:"Referencia(opcional)" %>
  </div>

  <div class="flex-form">
    <%= form.submit %>
    <%= link_to "Cancel", wallets_path %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<tr id="<%= dom_id income %>">
  <td class="td-date">
    <%= income.created_at.strftime("%Y/%m/%d") %>
  </td>
  
  <td class="td-description">
    <%= income.description.capitalize %>
  </td>
  
  <td class="td-value">
    <%= "+ #{number_to_currency(income.value)}" %>
  </td>
</tr>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Show this income", @income %> |
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render "form", income: @income, wallet:@wallet %>

<br>

<div>
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_income_path(@income) %> |
  <%= link_to "Back to wallet", wallets_path %>

  <%= button_to "Destroy this income", @income, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Walletapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="shortcut icon" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" type="image/x-icon">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/wallets/_form.html.erb
<%= form_with(model: wallet, class:" form") do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex-form">
    <label>
      <%# <i class="ion-location"></i> %>
      <%= image_tag("icons/card-credit-icon.png") %>
    </label>
    <%= form.text_field :name, placeholder:"Name of wallet" %>
    <%= form.submit %>
  </div>

        
  
<% end %>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>" class="wallet">

  <div class="container-wallet">
    <div class="wallet-group">
      <div class="wallet-title">
        <p>
          <%= wallet.name.capitalize %>
        </p>
        <small>
          <%= "No. 00#{756544250 + wallet.id}" %>
        </small>
      </div>

      <%= image_tag("icons/card-credit-icon.png") %>
    </div>
    <div class="wallet-group">
      <p>Cupo disponible:</p>

      <h3>
        <%= number_to_currency(wallet.balance) %>
      </h3>
    </div>
  </div>

</div>

app/views/wallets/edit.html.erb
<h1>Editing wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Show this wallet", @wallet %> |
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tus Cuentas</h1>

<div id="wallets" class="container">
  <% @wallets.each do |wallet| %>
    <%= link_to wallet_path(wallet) do %>
      <%= render wallet %>
    <%end%>
  <% end %>
</div>

<%= link_to "New wallet", new_wallet_path, class:"btn btn-shadow btn-border" %>

app/views/wallets/new.html.erb
<h1>New wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/show.html.erb
<%= render @wallet %>

<div>
  <%= link_to "Edit this wallet", edit_wallet_path(@wallet) %> |
  <%= link_to "Back to wallets", wallets_path %>
  <%= link_to "new income", new_income_wallets_path(@wallet) %>

  <%= button_to "Destroy this wallet", @wallet, method: :delete %>

  <div class="container mt-3 transaction">
    <h3 class="title">Tus movimientos</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="td-date">Fecha aplicación</th>
          <th class="td-description">Descripción</th>
          <th class="td-value">Monto</th>
        </tr>
      </thead>
      <tbody>
        <% @wallet.incomes.each do |income| %>
          <tr>
            <%= render income %>
          </tr>
        <% end %>
        
      </tbody>
    </table>
  
  
</div>